### ISSUE TITLE
Can't start it locally

### ISSUE THREAD

**Issue by berndgoetz** [making/blackhole#2]
When I try to run it locally, I get 

```
C:\Users\srzgob\workspaces\blackhole>java -Xms5m -Xmx5m -XX:MaxMetaspaceSize=24M -XX:ReservedCodeCacheSize=16M -XX:CompressedClassSpaceSize=8M -XX:MaxDirectMemorySize=8M -Xss5
12k -jar target/blackhole-1.0.0-SNAPSHOT.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: reactor.netty.ChannelBindException: Failed to bind on [0.0.0.0:8080]
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:133)
                at reactor.core.publisher.Mono.block(Mono.java:1517)
                at reactor.netty.http.server.HttpServer.bindNow(HttpServer.java:122)
                at reactor.netty.http.server.HttpServer.bindNow(HttpServer.java:106)
                at reactor.netty.http.server.HttpServer.bindUntilJavaShutdown(HttpServer.java:150)
                at am.ik.playground.App.main(App.java:31)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
                at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
                at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
                at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

Java: 
```
C:\Users\srzgob\workspaces\blackhole>java -version
openjdk version "11-ea" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11-ea+18)
OpenJDK 64-Bit Server VM 18.9 (build 11-ea+18, mixed mode)
```

Any insights on what might go wrong here?

**Comment by making** [comment]
I guess you have another process that listens on 8080

**Comment by berndgoetz** [comment]
Yes, you're right. What a rookie error! Thanks. Closing.
